name: Auto Merge Development to Clients

on:
  push:
    branches:
      - development
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  merge-to-clients:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        client-branch:
          [development-client1, development-client2, development-client3]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure all branches are fetched

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Merge development into ${{ matrix.client-branch }}
        run: |
          git checkout ${{ matrix.client-branch }}
          git pull origin ${{ matrix.client-branch }}
          git merge development --no-edit
          git push origin ${{ matrix.client-branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
