name: Auto Merge Development to Clients

on:
  push:
    branches:
      - development # Triggers when development branch is updated

jobs:
  merge-to-clients:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        client-branch: [develop-test1, develop-test2, develop-test3]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensures all branches are fetched

      - name: Configure Git
        run: |
          git config --global user.name "Ronith PR"
          git config --global user.email "ronithgsk@gmail.com"

      - name: Merge development into ${{ matrix.client-branch }}
        run: |
          git checkout ${{ matrix.client-branch }}
          git pull origin ${{ matrix.client-branch }}
          git merge development --no-edit
          git push origin ${{ matrix.client-branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
